### ISSUE TITLE
Passed test details no longer listing under Velocity headings

### ISSUE THREAD

**Issue by alanbar** [rjsmith/meteor-robotframework#13]
I have been using your package for 2 months and it has worked brilliantly. 
Today, I get "4 tests passed in 7 secs"  but details of the tests are not listed underneath, as previously.
However, details are still in the green Test Report.
Problem also occurring in previous programs that were listing ok.
Is there some file that I need to clean out?

**Comment by rjsmith** [comment]
Hi,

Have you upgraded your robot framework version  to 2.9 recently? I
understand they have made changes to the format of the output.XML file. I
have not yet had a chance / need to look into this myself yet...

**Comment by alanbar** [comment]
No, all I do is  'meteor add rsbatech:robotframework'

**Comment by alanbar** [comment]
Hi, dumb user here!
If I click on circle below "4 tests passed in 7 secs", then I can click on 'Show passing tests' and in fact it does.
I must have inadvertently clicked on this circle.  
It might be a good idea for Velocity to leave this option on, by default, as I had forgotten it was required to show the passing tests.
