### ISSUE TITLE
Using virtualenv and meteor-robotframework

### ISSUE THREAD

**Issue by rosatolen** [rjsmith/meteor-robotframework#14]
Hi!

I'd like to use virtualenv to use robotframework with older versions of python. When I use virtualenv to set up an environment with python2, install robotframework and run `meteor`, I get this error: 

```
=> Started proxy.                             
=> Started MongoDB.                                                                
env/lib/python2.7/site-packages/docutils/writers/s5_html/themes/default/slides.css: warn: there are some @import rules those are not taking effect as they are required to be in the beginning of
the file
=> Errors prevented startup:                  

   While building the application:
   env/lib/python2.7/site-packages/Selenium2Library/resources/firefoxprofile/prefs.js:1:15: Unexpected token ILLEGAL
   env/lib/python2.7/site-packages/robot/htmldata/libdoc/libdoc.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   env/lib/python2.7/site-packages/robot/htmldata/rebot/log.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   env/lib/python2.7/site-packages/robot/htmldata/rebot/report.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   env/lib/python2.7/site-packages/robot/htmldata/testdoc/testdoc.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
```

It looks like there are some conflicts between these python virtual environment files located in the home directory of my project. When I move the virtual environment folder outside of the home directory, I don't get these errors and robotframework runs properly.

Any idea on how to fix this? 

Thanks!

**Comment by rjsmith** [comment]
Hi,

Sorry, I have no experience using virtualenv.
Any files placed in the meteor project folder will be parsed by meteor.
You could try renaming the `env` folder in your meteor project root folder
to `.env`.  This will stop the meteor build engine from parsing the
contents of that folder.
