### ISSUE TITLE
Cannot run meteor-robotframework and sanjo:jasmine tests on same project

### ISSUE THREAD

**Issue by rjsmith** [rjsmith/meteor-robotframework#4]
When I try to add rsbatech:robotframework and sanjo:jasmine packages to the same project, meteor throws a build error.  I have been able to create a minimum repo that reproduces the issue:

https://github.com/rjsmith/bugrepo-jasmine-rf

@sanjo, I'd be very grateful if you could clone the repo and see if you can help spot what the issue might be.

Originally posted on velocity-core Google Groups here:

https://groups.google.com/forum/#!topic/velocity-core/F3k4ArOI43M

**Comment by rjsmith** [comment]
So, I have just found that exactly the same error occurs if I remove all test packages then add cucumber and jasmine in this order:

`meteor add xolvio:cucumber`
then:
`meteor add sanjo:jasmine`
Take look at the cucumber-jasmine branch in the bugrepo repo: https://github.com/rjsmith/bugrepo-jasmine-rf/tree/cucumber-jasmine

However, if the order is reversed, it seems to work just fine.

Also, xolvio:cucumber and rsbatech:robotframework in the same project (without sanjo:jasmine) seems to work fine too.

So, I am no longer sure this is to do with rsbatech:robotframework alone.

```
W20150312-21:26:19.942(0)? (STDERR) /Users/richardsmith/.meteor/packages/meteor-tool/.1.0.41.1bm7kmi++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150312-21:26:19.942(0)? (STDERR)                         throw(ex);
W20150312-21:26:19.944(0)? (STDERR)                               ^
W20150312-21:26:19.953(0)? (STDERR) ReferenceError: Jasmine is not defined
W20150312-21:26:19.953(0)? (STDERR)     at Jasmine.onTest.jasmine.addMatchers.toBePlaying.compare.player (packages/velocity:test-proxy/tests/jasmine/server/integration/sample/spec/PlayerSpec.js:1:1)
W20150312-21:26:19.953(0)? (STDERR)     at /Users/richardsmith/Projects/meteor-test/bugrepo-jasmine-rf/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:69:4
W20150312-21:26:19.953(0)? (STDERR)     at /Users/richardsmith/Projects/meteor-test/bugrepo-jasmine-rf/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:176:3
W20150312-21:26:19.954(0)? (STDERR)     at /Users/richardsmith/Projects/meteor-test/bugrepo-jasmine-rf/.meteor/local/build/programs/server/boot.js:205:10
W20150312-21:26:19.954(0)? (STDERR)     at Array.forEach (native)
W20150312-21:26:19.954(0)? (STDERR)     at Function._.each._.forEach (/Users/richardsmith/.meteor/packages/meteor-tool/.1.0.41.1bm7kmi++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150312-21:26:19.954(0)? (STDERR)     at /Users/richardsmith/Projects/meteor-test/bugrepo-jasmine-rf/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
```

**Comment by SamHatoum** [comment]
and if you reverse the order with robot, it still doesn't work?

**Comment by ghost** [comment]
I will have a more detailed look soon. Probably something regarding: https://github.com/Sanjo/meteor-jasmine/blob/master/server/integration/ServerIntegrationTestFramework.js#L19-L22

**Comment by SamHatoum** [comment]
I was thinking maybe this:

https://github.com/Sanjo/meteor-jasmine/blob/master/package.js#L48

**Comment by rjsmith** [comment]
It does work for jasmine + rf in the repo project 

Let me try to summarise:

| First `meteor add` | Second `meteor add` | Status |
| --- | --- | --- |
| sanjo:jasmine | n/a | OK |
| rsbatech:robotframework | n/a | OK |
| xolvio:cucumber | n/a | OK |
| rsbatech:robotframework | sanjo:jasmine | ERRORS |
| sanjo:jasmine | rsbatech:robotframework | OK |
| xolvio:cucumber | sanjo:jasmine | ERRORS |
| sanjo:jasmine | xolvio:cucumber | OK |
| rsbatech:robotframework | xolvio:cucumber | OK |
| xolvio:cucumber | rsbatech:robotframework | OK *\* but if test-proxy local package is not deleted after removing sanjo:jasmine, get the same error. |

**Comment by ghost** [comment]
Fix: https://github.com/meteor-velocity/node-soft-mirror/pull/29

**Comment by rjsmith** [comment]
Now resolved with latest velocity-core0.6.0 and RF package 0.3.0, thanks @Sanjo  !
